services:
  - type: web
    name: news-wires-app
    env: php
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
